version: 1

goos: linux
goarch: arm64
cgo: "0"

flags:
  - -trimpath

ldflags:
  - "-s -w"
  - "-X main.version={{ .Env.VERSION }}"
  - "-X main.commit={{ .Env.COMMIT }}"
  - "-X main.commitDate={{ .Env.COMMIT_DATE }}"


binary: bdpatch-linux-arm64
